### ISSUE TITLE
An error occurred after the project was run again.

### ISSUE THREAD

**Issue by zilin-zhou** [SamYuan1990/Probe#106]
After I cloned the project and ran it on my ubuntu20.04 system, I checked the log and the whole project was finished. However, the data of TPS Relationship with BatchTimeout and TPS relationship with MaxMessageCount cannot be seen. And errors have occurred. The result is as follows: Have you met this kind of mistake, please help me.
<img width="812" alt="1" src="https://user-images.githubusercontent.com/95197986/159110526-790bb4b3-c7f6-4d01-b642-268101fa0338.png">
<img width="876" alt="微信图片_20220319143833" src="https://user-images.githubusercontent.com/95197986/159110529-4658ecb2-557a-4a02-afca-b78bf6a0bc95.png">
<img width="922" alt="微信图片_20220319143842" src="https://user-images.githubusercontent.com/95197986/159110530-453a3b71-43c7-4511-af75-3ff42699881e.png">

**Comment by SamYuan1990** [comment]
@zilin-zhou , thanks for your question.
I found it seems some file missing or mis deleted in previous commit.
I just pushed some commit to fix it, you are able to have a try with https://github.com/SamYuan1990/Probe/commit/2ffbe87e20ddb9b6c9a6cfd679c64acab71b0a40
For next time, I suggest you try to use your chrome in developer mode to find more details in URL resource list.
