### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Testchuchen** [SamYuan1990/Probe#111]
root@famebamboo:/home/go/src/Probe-1.0.1# npm start

> probe@1.0.0 start /home/go/src/Probe-1.0.1
> node ./bin/www

/home/go/src/Probe-1.0.1/node_modules/universalify/index.js:15
  }, 'name', { value: fn.name })
                         ^

TypeError: Cannot read property 'name' of undefined
    at exports.fromCallback (/home/go/src/Probe-1.0.1/node_modules/universalify/index.js:15:26)
    at Object.<anonymous> (/home/go/src/Probe-1.0.1/node_modules/fs-extra/lib/fs/index.js:57:27)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/go/src/Probe-1.0.1/node_modules/fs-extra/lib/index.js:5:6)

**Comment by SamYuan1990** [comment]
can't reproduce for either main or tag 1.0.1
```
yuanyi@yuanyideMacBook-Pro Probe % git log -1
commit 7a43b40bc2baf8a3e2b6f4b8f5fe343734fc9fc1 (HEAD -> main, origin/main, origin/HEAD)
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Sun Apr 3 11:05:26 2022 +0800

    Bump minimist from 1.2.5 to 1.2.6 (#110)
    
    Bumps [minimist](https://github.com/substack/minimist) from 1.2.5 to 1.2.6.
    - [Release notes](https://github.com/substack/minimist/releases)
    - [Commits](https://github.com/substack/minimist/compare/1.2.5...1.2.6)
    
    ---
    updated-dependencies:
    - dependency-name: minimist
      dependency-type: indirect
    ...
    
    Signed-off-by: dependabot[bot] <support@github.com>
    
    Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
yuanyi@yuanyideMacBook-Pro Probe % npm start

> probe@1.0.0 start
> node ./bin/www
```

```
yuanyi@yuanyideMacBook-Pro Probe % git log -1
commit 8e4cb789010257ceb543e4026550bf31b2f4208d (HEAD, tag: v1.0.1)
Author: Sam Yuan <yy19902439@126.com>
Date:   Sat Mar 19 19:00:17 2022 +0800

    update (#108)
    
    Signed-off-by: Sam Yuan <yy19902439@126.com>
yuanyi@yuanyideMacBook-Pro Probe % npm start

> probe@1.0.0 start
> node ./bin/www
```
