### ISSUE TITLE
Grafana version problem

### ISSUE THREAD

**Issue by Elegenthus** [SamYuan1990/Probe#58]
When I run `docker-compose up -d` to start `grafana` container, the following error comes
> GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied

I find that it may be caused by the version of grafana and `grafana:5.0.0` can solve this problem([Prometheus-部署Grafana](https://www.jianshu.com/p/83c4ea8dfb8e)). 
So I change grafana image version in `monitor/docker-compose.yaml` 

> grafana:
    container_name: grafana
    # image:   grafana/grafana
    image: grafana/grafana:5.0.0
    ports:
      - "3001:3000"
    volumes:
      - ./prometheus/grafana/grafana:/var/lib/grafana
      - ./prometheus/grafana/conf:/usr/share/grafana/conf
    networks:
      - monitor
    
And I can visit `http://localhost:3001/` for `grafana` with `admin/admin` now.
If you have better solution, pls tell me.

**Comment by SamYuan1990** [comment]
> When I run `docker-compose up -d` to start `grafana` container, the following error comes
> 
> > GF_PATHS_DATA='/var/lib/grafana' is not writable.
> > You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
> > mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
> 
> I find that it may be caused by the version of grafana and `grafana:5.0.0` can solve this problem([Prometheus-部署Grafana](https://www.jianshu.com/p/83c4ea8dfb8e)).
> So I change grafana image version in `monitor/docker-compose.yaml`
> 
> > grafana:
> > container_name: grafana
> > # image:   grafana/grafana
> > image: grafana/grafana:5.0.0
> > ports:
> > - "3001:3000"
> > volumes:
> > - ./prometheus/grafana/grafana:/var/lib/grafana
> > - ./prometheus/grafana/conf:/usr/share/grafana/conf
> > networks:
> > - monitor
> 
> And I can visit `http://localhost:3001/` for `grafana` with `admin/admin` now.
> If you have better solution, pls tell me.

Well I just use images below with root permissions. if you having issue with using root permissions to start grafana, I suppose you'd better to ask https://github.com/grafana/grafana/issues for grafana usage.

Disk permission, generally speaking is out of Probe scope.
if you want to specific grafana version, you can tag the image locally.
```
docker images
prom/pushgateway                                latest                                           e3e0e3c76855   2 weeks ago     19.4MB
prom/prometheus                                 latest                                           0bc82119c95b   5 weeks ago     169MB
prom/node-exporter                              latest                                           0e0218889c33   6 months ago    26.4MB
google/cadvisor                                 latest                                           eb1210707573   2 years ago     69.6MB
```
