### ISSUE TITLE
Could not get script via 'curl -vsS https://raw.githubusercontent.com/hyperledger/fabric/master/scripts/bootstrap.sh | bash'

### ISSUE THREAD

**Issue by lyp830414** [SamYuan1990/Probe#76]
**Issue description**
As curl could not support https( unless user try to manually compile and install curl code with enable 'https' feature  )

Then it failed after I tried ‘ curl -vsS https://raw.githubusercontent.com/hyperledger/fabric/master/scripts/bootstrap.sh | bash’, shown as following figure.

![image](https://user-images.githubusercontent.com/13618985/106742393-f267aa00-6657-11eb-8e32-339a4f8ea57a.png)

I haven't found a good way about how to download the script automatically, so I did it by manual :-)

**Proposal**
Shall we notice user to do it by manual in README? Or any approach the way to download & operate it .

**Comment by SamYuan1990** [comment]
@lyp830414 , could you please fix this bug via pr?
in fact, the shell script is https://github.com/hyperledger/fabric/blob/master/scripts/bootstrap.sh
or we can modify the document with download 
`https://github.com/hyperledger/fabric/blob/master/scripts/bootstrap.sh` and run?
