### ISSUE TITLE
Problem occurs when test probe under Centos 7.X

### ISSUE THREAD

**Issue by lyp830414** [SamYuan1990/Probe#82]
Something wrong when I test the probe.
    1. As I obey the steps from REAME, npm install and ./bootstrap.sh, then copy the configuration sh -> test-network.
    2. Visit the web with myIP:3000,  then I choose the 'TestNetwork Sample' , and do "Submit" at the end of web.
    3. I found the chain could not bring up in backend (no docker container), and the npm report issues in my attachment.

My testbed:
     - Linux CentOS7-135 3.10.0-1160.6.1.el7.x86_64

(More test notes I have remarked them at [fabric-performance-wiki/issues/14](https://github.com/Hyperledger-TWGC/fabric-performance-wiki/issues/14))
        
[liyiping-probe-issue-log.txt](https://github.com/SamYuan1990/Probe/files/5949193/liyiping-probe-issue-log.txt)
@SamYuan1990

**Comment by SamYuan1990** [comment]
there two option to fix.
option a:
`curl -sSL https://bit.ly/2ysbOFE | bash -s -- 2.2.2 1.4.9` to download fabric sample to local.
option b:
remove -i 2.2 to use latest version.

**Comment by lyp830414** [comment]
## 1. 问题背景

在测试Probe过程中，发现通道和链码都构建出错，后台链是fabric-2.2 release，不久后所有docker被释放。

由于Probe目前在code中设置使用的fabric网络是V2.2，但目前fabric-samples已经是V2.3版本了。

这造成了测试CASE和底层链不匹配的问题，导致测试和链异常。



## 2. 问题的提出

由于存在fabric-samples版本和Probe代码指定的fabric版本不匹配，我们需要找到一种不改代码让用户可以选择切换版本，同时保证两者匹配的方法。



## 3. 问题解决思路

1. 设置环境变量export FABRIC_VERSION=2.2

2. 代码相关处要增加读取环境变量，将版本号改为环境变量

   涉及改动文件：
    
![image](https://user-images.githubusercontent.com/13618985/107334621-e8c7c180-6af1-11eb-983a-53234c1d6a9b.png)


3. 改动示例

   ```
       ......
        cmdType:"Shell",args:["./network.sh","up","createChannel","-i","2.2"]},
   - >  cmdType:"Shell",args:["./network.sh","up","createChannel","-i", process.env.FABRIC_VERSION]}
        .....
   ```

  **【注】**

​        不太熟悉js/jsx和pipeline语法，待确定是否可以这么操作。
         @SamYuan1990

**Comment by SamYuan1990** [comment]
三行配置的事情。。。
```
cd fabric-sample
git checkout ....
cd ..
```
