### ISSUE TITLE
Result problem of latest version Probe

### ISSUE THREAD

**Issue by lyp830414** [SamYuan1990/Probe#84]
I've rebased the latest version of Probe which contains bugfix [#83](https://github.com/SamYuan1990/Probe/pull/83)

1. I choosed the 'TestnetowrkSample' at web site , the submit it.
2. Here is my parameters
![image](https://user-images.githubusercontent.com/13618985/107465193-d191de00-6b9c-11eb-99f4-a9520eaad6d8.png)

3. Wait until the test done, then the result shown as following
    
     The problem is that the axis of X, Y has no remark & no number.

![image](https://user-images.githubusercontent.com/13618985/107465069-84157100-6b9c-11eb-91ad-1695de4453c8.png)

![image](https://user-images.githubusercontent.com/13618985/107465310-17e73d00-6b9d-11eb-8d53-eaf50374b3d6.png)

![image](https://user-images.githubusercontent.com/13618985/107465498-714f6c00-6b9d-11eb-8f4e-005198847742.png)

4. Here I attach the backend partly log, due to I could not catch them all.
   
[liyiping-probe-issue-partly-log.txt](https://github.com/SamYuan1990/Probe/files/5955897/liyiping-probe-issue-partly-log.txt)

@SamYuan1990

**Comment by SamYuan1990** [comment]
`time="2021-02-10T04:23:44Z" level=error msg="Err processing proposal: %!s(<nil>), status: 500, message: error in simulation: failed to execute transaction 88abdf68222698a3d893cb1a9145bf71e7022d1e75255b993d2070c7edfc46bb: could not launch chaincode basic_1.0:4ec191e793b27e953ff2ede5a8bcc63152cecb1e4c3f301a26e22692c61967ad: chaincode registration failed: error starting container: error starting container: API error (404): network _test not found, addr: localhost:7051 \n"`

see discussion here https://github.com/hyperledger/fabric-samples/pull/412

**Comment by SamYuan1990** [comment]
> I've rebased the latest version of Probe which contains bugfix [#83](https://github.com/SamYuan1990/Probe/pull/83)
> 
> 1. I choosed the 'TestnetowrkSample' at web site , the submit it.
> 2. Here is my parameters
>    ![image](https://user-images.githubusercontent.com/13618985/107465193-d191de00-6b9c-11eb-99f4-a9520eaad6d8.png)
> 3. Wait until the test done, then the result shown as following
>    The problem is that the axis of X, Y has no remark & no number.
> 
> ![image](https://user-images.githubusercontent.com/13618985/107465069-84157100-6b9c-11eb-91ad-1695de4453c8.png)
> 
> ![image](https://user-images.githubusercontent.com/13618985/107465310-17e73d00-6b9d-11eb-8d53-eaf50374b3d6.png)
> 
> ![image](https://user-images.githubusercontent.com/13618985/107465498-714f6c00-6b9d-11eb-8f4e-005198847742.png)
> 
> 1. Here I attach the backend partly log, due to I could not catch them all.
> 
> [liyiping-probe-issue-partly-log.txt](https://github.com/SamYuan1990/Probe/files/5955897/liyiping-probe-issue-partly-log.txt)
> 
> @SamYuan1990

you'd better adjust fabric-network according to your fabric version.

**Comment by lyp830414** [comment]
Got the message. I'd like to reproduce & try network trouble shooting as I back to office (after the Spring Festival) due to the testbed is set on my office servers :-)

**Comment by lyp830414** [comment]
My test-bed issue has been fixed now & I've concluded them into fabric-performance-wiki [#14] (https://github.com/Hyperledger-TWGC/fabric-performance-wiki/issues/14) now. Now close the issue :-)
