### ISSUE TITLE
https://raw.githubusercontent.com/hyperledger/fabric/master/scripts/bootstrap.sh cannot be reached.

### ISSUE THREAD

**Issue by lyp830414** [SamYuan1990/Probe#86]
As I access the https://raw.githubusercontent.com/hyperledger/fabric/master/scripts/bootstrap.sh, the web cannot be reached now (I've tried to ping "raw.githubusercontent.com" then fail, both under Win7 & Ubuntu 18) . 

![image](https://user-images.githubusercontent.com/13618985/107846844-05ca0080-6e22-11eb-9686-1e7ff378d7fb.png)

Does the script's url need to be changed to that of the fabric project shown as following in the read me document?
        https://github.com/hyperledger/fabric/blob/master/scripts/bootstrap.sh

**Comment by SamYuan1990** [comment]
to be honest, I don't want to argue with network issue too much. either url looks fine for me.

**Comment by lyp830414** [comment]
It is just a test-bed issue(here in Shanghai) at home... so close it.
